export const searchChallengeByUser = /* GraphQL */ `
  query searchChallengeByUser($userId: String!) {
    listUserChallenges(limit: 1000, filter: {userId: {eq: $userId}}) {
      items {
        id
        challengeId
        challenge {
          id
          title
          increase
          task1Name
          task2Name
          task3Name
          task4Name
          task5Name
          task6Name
          task7Name
          task8Name
          task9Name
          task10Name
          task11Name
          task12Name
          task13Name
          task14Name
          task15Name
          task16Name
          task17Name
          task18Name
          task19Name
          task20Name
          task21Name
          task22Name
          task23Name
          task24Name
          task25Name
          task26Name
          task27Name
          task28Name
          task29Name
          task30Name
        }
        userId
        startDate
        isValid
        task1IsDone
        task1Date
        task2IsDone
        task2Date
        task3IsDone
        task3Date
        task4IsDone
        task4Date
        task5IsDone
        task5Date
        task6IsDone
        task6Date
        task7IsDone
        task7Date
        task8IsDone
        task8Date
        task9IsDone
        task9Date
        task10IsDone
        task10Date
        task11IsDone
        task11Date
        task12IsDone
        task12Date
        task13IsDone
        task13Date
        task14IsDone
        task14Date
        task15IsDone
        task15Date
        task16IsDone
        task16Date
        task17IsDone
        task17Date
        task18IsDone
        task18Date
        task19IsDone
        task19Date
        task20IsDone
        task20Date
        task21IsDone
        task21Date
        task22IsDone
        task22Date
        task23IsDone
        task23Date
        task24IsDone
        task24Date
        task25IsDone
        task25Date
        task26IsDone
        task26Date
        task27IsDone
        task27Date
        task28IsDone
        task28Date
        task29IsDone
        task29Date
        task30IsDone
        task30Date
      }
    }

    listGroupChallenges(limit: 1000, filter: {userId: {eq: $userId}}) {
      items {
        challengeId
        challenge {
          id
          title
          increase
          task1Name
          task2Name
          task3Name
          task4Name
          task5Name
          task6Name
          task7Name
          task8Name
          task9Name
          task10Name
          task11Name
          task12Name
          task13Name
          task14Name
          task15Name
          task16Name
          task17Name
          task18Name
          task19Name
          task20Name
          task21Name
          task22Name
          task23Name
          task24Name
          task25Name
          task26Name
          task27Name
          task28Name
          task29Name
          task30Name
        }
        userId
        groupId
        startDate
        isValid
        task1IsDone
        task1Date
        task2IsDone
        task2Date
        task3IsDone
        task3Date
        task4IsDone
        task4Date
        task5IsDone
        task5Date
        task6IsDone
        task6Date
        task7IsDone
        task7Date
        task8IsDone
        task8Date
        task9IsDone
        task9Date
        task10IsDone
        task10Date
        task11IsDone
        task11Date
        task12IsDone
        task12Date
        task13IsDone
        task13Date
        task14IsDone
        task14Date
        task15IsDone
        task15Date
        task16IsDone
        task16Date
        task17IsDone
        task17Date
        task18IsDone
        task18Date
        task19IsDone
        task19Date
        task20IsDone
        task20Date
        task21IsDone
        task21Date
        task22IsDone
        task22Date
        task23IsDone
        task23Date
        task24IsDone
        task24Date
        task25IsDone
        task25Date
        task26IsDone
        task26Date
        task27IsDone
        task27Date
        task28IsDone
        task28Date
        task29IsDone
        task29Date
        task30IsDone
        task30Date
      }
    }
  }
`;
